export const PACKOUT_ITEMS = [
  {
    key: "sofa",
    label: "Sofa",
    keywords: ["sofa", "couch", "sectional"],
    category: "furniture",
    base: 55,
    packOut: 25,
    clean: 15,
    storage: 10,
    reset: 20,
  },
  {
    key: "bed",
    label: "Bed",
    keywords: ["bed", "mattress"],
    category: "furniture",
    base: 65,
    packOut: 30,
    clean: 20,
    storage: 12,
    reset: 25,
  },
  {
    key: "dresser",
    label: "Dresser",
    keywords: ["dresser"],
    category: "furniture",
    base: 45,
    packOut: 20,
    clean: 15,
    storage: 10,
    reset: 20,
  },
  {
    key: "tv",
    label: "Television",
    keywords: ["tv", "television"],
    category: "electronics",
    base: 40,
    packOut: 18,
    clean: 10,
    storage: 8,
    reset: 15,
  },
  {
    key: "lamp",
    label: "Lamp",
    keywords: ["lamp"],
    category: "decor",
    base: 15,
    packOut: 6,
    clean: 5,
    storage: 4,
    reset: 6,
  },
  {
    key: "decor",
    label: "Decor",
    keywords: ["decor", "vase", "plant"],
    category: "misc",
    base: 10,
    packOut: 5,
    clean: 4,
    storage: 3,
    reset: 5,
  },
];