export const PACKOUT_ITEMS = [
  {
    key: "sofa",
    label: "Sofa",
    keywords: ["sofa", "couch", "sectional", "loveseat"],
    category: "furniture",
    base: 55,
    packOut: 25,
    clean: 15,
    storage: 10,
    reset: 20,
  },
  {
    key: "chair",
    label: "Chair",
    keywords: ["chair", "recliner", "stool", "accent chair"],
    category: "furniture",
    base: 22,
    packOut: 10,
    clean: 6,
    storage: 4,
    reset: 8,
  },
  {
    key: "table",
    label: "Table",
    keywords: ["table", "desk", "coffee table", "end table", "nightstand"],
    category: "furniture",
    base: 28,
    packOut: 12,
    clean: 8,
    storage: 5,
    reset: 10,
  },
  {
    key: "bed",
    label: "Bed",
    keywords: ["bed", "mattress", "headboard", "footboard"],
    category: "furniture",
    base: 65,
    packOut: 30,
    clean: 20,
    storage: 12,
    reset: 25,
  },
  {
    key: "dresser",
    label: "Dresser",
    keywords: ["dresser", "chest", "wardrobe"],
    category: "furniture",
    base: 48,
    packOut: 20,
    clean: 15,
    storage: 10,
    reset: 20,
  },
  {
    key: "tv",
    label: "Television",
    keywords: ["tv", "television", "monitor"],
    category: "electronics",
    base: 38,
    packOut: 18,
    clean: 10,
    storage: 8,
    reset: 15,
  },
  {
    key: "computer",
    label: "Computer",
    keywords: ["computer", "pc", "laptop", "printer"],
    category: "electronics",
    base: 32,
    packOut: 14,
    clean: 8,
    storage: 6,
    reset: 12,
  },
  {
    key: "lamp",
    label: "Lamp",
    keywords: ["lamp", "light", "floor lamp", "table lamp"],
    category: "decor",
    base: 14,
    packOut: 6,
    clean: 5,
    storage: 4,
    reset: 6,
  },
  {
    key: "art",
    label: "Wall Art",
    keywords: ["art", "picture", "frame", "mirror", "painting"],
    category: "decor",
    base: 12,
    packOut: 7,
    clean: 6,
    storage: 5,
    reset: 7,
  },
  {
    key: "rug",
    label: "Rug",
    keywords: ["rug", "carpet runner"],
    category: "decor",
    base: 18,
    packOut: 8,
    clean: 7,
    storage: 5,
    reset: 8,
  },
  {
    key: "decor",
    label: "Decor",
    keywords: ["decor", "vase", "plant", "book", "books", "knickknack"],
    category: "misc",
    base: 10,
    packOut: 5,
    clean: 4,
    storage: 3,
    reset: 5,
  },
  {
    key: "box",
    label: "Box / Tote",
    keywords: ["box", "boxes", "bin", "tote", "container"],
    category: "misc",
    base: 9,
    packOut: 4,
    clean: 2,
    storage: 4,
    reset: 4,
  },
];